export const PLANETS = [
    /* - - Sun - - */
    {
        name: "sun",
		displayName: "The Sun",
        description: "Yellow dwarf star",
		year: "230 milion years",
        day: null,
        distanceFromSun: -1,
        radius: 695508,
		TimesLarger: 109.2,
		orbitalVelocity: 0,
        orbitObject: null,
        orbitalRadius: 0,
        scaledOrbitalRadius: 0,
        rotationVelocity: 2,
        orbitalInclination: 0,
    },
    /* - - Sun - - */

    /* - - Planets - - */
    {
        name: "mercury",
		displayName: "Mercury",
        description: "Swift Planet",
		year: "88 Earth days",
        day: "59 Earth days",
        distanceFromSun: 0.4,
        radius: 2439.7,
		TimesLarger: 0.38,
		orbitalVelocity: 47.9, 
        orbitObject: "sun",
        orbitalRadius: 57909050, 
        scaledOrbitalRadius: 30, 
        rotationVelocity: 0.003,
        orbitalInclination: 3.3,
    },
    {
        name: "venus",
		displayName: "Venus",
        description: "Morning Star",
		year: "225 Earth days",
        day: "243 Earth days",
        distanceFromSun: 0.7,
        radius: 6051.8,
		TimesLarger: 0.9,
		orbitalVelocity: 35.0, 
        orbitObject: "sun",
        orbitalRadius: 108200000, 
        scaledOrbitalRadius: 35, 
        rotationVelocity: 0.003,
        orbitalInclination: 3.8,
    },
    {
        name: "earth",
		displayName: "Earth",
        description: "Blue Planet",
		year: "365.25 Earth days",
        day: "23.9 hours",
        distanceFromSun: 1,
        radius: 6371,
		TimesLarger: -1,
		orbitalVelocity: 29.8, //29.8
        orbitObject: "sun",
        orbitalRadius: 149600000, 
        scaledOrbitalRadius: 40, //149.6, //149600000 // Scale: 1m : 1 000 000km
        rotationVelocity: 0.46,
        orbitalInclination: 3,
    },
    {
        name: "mars",
		displayName: "Mars",
        description: "Red Planet",
		year: "1.88 Earth years",
        day: "24.6 hours",
        distanceFromSun: 1.5,
        radius: 3389.5,
		TimesLarger: 0.52,
		orbitalVelocity: 24.1, 
        orbitObject: "sun",
        orbitalRadius: 227939366, 
        scaledOrbitalRadius: 45, 
        rotationVelocity: 0.241,
        orbitalInclination: 5.6,
    },
    {
        name: "jupiter",
		displayName: "Jupiter",
        description: "Giant Planet",
		year: "11.86 Earth years",
        day: "9.93 hours",
        distanceFromSun: 5.1,
        radius: 69911,
		TimesLarger: 11,
		orbitalVelocity: 24.1, 
        orbitObject: "sun",
        orbitalRadius: 778412027, 
        scaledOrbitalRadius: 72, 
        rotationVelocity: 12.6,
        orbitalInclination: 6,
    },
    {
        name: "saturn",
		displayName: "Saturn",
        description: "Ringed Planet",
		year: "29.45 Earth years",
        day: "10.7 hours",
        distanceFromSun: 9.5,
        radius: 58232,
		TimesLarger: 9.1,
		orbitalVelocity: 9.7, 
        orbitObject: "sun",
        orbitalRadius: 1433530000, 
        scaledOrbitalRadius: 108, 
        rotationVelocity: 9.87,
        orbitalInclination: 5.5,
    },
    {
        name: "uranus",
		displayName: "Uranus",
        description: "Ice Giant",
		year: "84 Earth years",
        day: "17 hours",
        distanceFromSun: 19.8,
        radius: 25362,
		TimesLarger: 4,
		orbitalVelocity: 6.8, 
        orbitObject: "sun",
        orbitalRadius: 2870972000, 
        scaledOrbitalRadius: 135, 
        rotationVelocity: 2.59,
        orbitalInclination: 6.5,
    },
    {
        name: "neptune",
		displayName: "Neptune",
        description: "Big Blue Planet",
		year: "164 Earth years",
        day: "16 hours",
        distanceFromSun: 30.1,
        radius: 24622,
		TimesLarger: 3.9,
		orbitalVelocity: 5.4, 
        orbitObject: "sun",
        orbitalRadius: 4514953000, 
        scaledOrbitalRadius: 170, 
        rotationVelocity: 2.6,
        orbitalInclination: 6.4,
    },
    /* - - Sun - - */

    /* - - Moons - - */
    {
        name: "moon",
		displayName: "Earth's Moon",
        description: "The brightest object in the night sky",
		year: "27 days",
        radius: 1737.5,
		TimesLarger: 0.27,
        distance: "385000 km",
		orbitalVelocity: 1.022,
        orbitObject: "earth",
        orbitalRadius: 385000, 
        scaledOrbitalRadius: 3,
        rotationVelocity: 0.966,
        orbitalInclination: 5,
    }
    /* - - Sun - - */
]