export const PLANETS = [
    /* - - Sun - - */
    {
        name: "sun",
        displayName: "The Sun",
        caption: "Yellow dwarf star",
        description: "The Sun is the center of our solar system and source of life on Earth. The temperature in Sun's core is about 15 million °C (27 million °F).",
        year: "230 milion Earth years",
        day: null,
        radius: 695508,
        meanTemp: 5500,
        timesLarger: 109.2,
        orbitalVelocity: 0,
        orbitObject: null,
        orbitalRadius: 0,
        scaledOrbitalRadius: 0,
        rotationVelocity: 2,
        orbitalInclination: 0,
        axialTilt: 7.25,
    },
    /* - - Sun - - */

    /* - - Planets - - */
    {
        name: "mercury",
        displayName: "Mercury",
        caption: "Swift Planet",
        description: "Mercury is the fastest and smallest planet in our solar system. On the surface, the Sun would appear 3 times as large as it does from Earth.",
        year: "88 Earth days",
        day: "59 Earth days",
        moons: 0,
        distanceFromSun: 0.4,
        minTemp: -170,
        maxTemp: 449,
        radius: 2439.7,
        timesLarger: 0.38,
        orbitalVelocity: 47.9, 
        orbitObject: "sun",
        orbitalRadius: 57909050, 
        scaledOrbitalRadius: 24, 
        rotationVelocity: 0.003,
        orbitalInclination: 7,
        axialTilt: 0.03,
    },
    {
        name: "venus",
        displayName: "Venus",
        caption: "Morning Star",
        description: "Venus is the hottest planet in our solar system. This is caused by its thick atmosphere which traps heat and causes greenhouse effect.",
        year: "225 Earth days",
        day: "243 Earth days",
        moons: 0,
        distanceFromSun: 0.7,
        meanTemp: 465,
        radius: 6051.8,
        timesLarger: 0.9,
        orbitalVelocity: 35.0, 
        orbitObject: "sun",
        orbitalRadius: 108200000, 
        scaledOrbitalRadius: 31, 
        rotationVelocity: 0.003,
        orbitalInclination: 3.4,
        axialTilt: 177,
    },
    {
        name: "earth",
        displayName: "Earth",
        caption: "Blue Planet",
        description: "Earth is the only planet in our solar system with liquid water on its surface. The atmosphere allows us humans to breathe, while it also protects us from meteoroids.",
        year: "365.25 Earth days",
        day: "23.9 hours",
        moons: 1,
        distanceFromSun: 1,
        minTemp: -89,
        maxTemp: 58,
        radius: 6371,
        timesLarger: -1,
        orbitalVelocity: 29.8,
        orbitObject: "sun",
        orbitalRadius: 149600000, 
        scaledOrbitalRadius: 37,
        rotationVelocity: 0.46,
        orbitalInclination: 0,
        axialTilt: 23.44,
    },
    {
        name: "mars",
        displayName: "Mars",
        caption: "Red Planet",
        description: "Mars is our best candidate for living outside of Earth. It is the only planet we've sent rovers to. Perseverance rover's Mars samples should make it to Earth in 2033.",
        year: "1.88 Earth years",
        day: "24.6 hours",
        moons: 2,
        distanceFromSun: 1.5,
        minTemp: -125,
        maxTemp: 20,
        radius: 3389.5,
        timesLarger: 0.52,
        orbitalVelocity: 24.1, 
        orbitObject: "sun",
        orbitalRadius: 227939366, 
        scaledOrbitalRadius: 45, 
        rotationVelocity: 0.241,
        orbitalInclination: 1.8,
        axialTilt: 25.19,
    },
    {
        name: "jupiter",
        displayName: "Jupiter",
        caption: "Giant Planet",
        description: "Jupiter is the largest planet in our solar system. The Great Red Spot is Jupiter's super storm that is twice the size of Earth and has raged for more than 100 years.",
        year: "11.86 Earth years",
        day: "9.93 hours",
        moons: 79,
        distanceFromSun: 5.1,
        meanTemp: -110,
        radius: 69911,
        timesLarger: 11,
        orbitalVelocity: 24.1, 
        orbitObject: "sun",
        orbitalRadius: 778412027, 
        scaledOrbitalRadius: 72, 
        rotationVelocity: 12.6,
        orbitalInclination: 1.3,
        axialTilt: 3.13,
    },
    {
        name: "saturn",
        displayName: "Saturn",
        caption: "Ringed Planet",
        description: "Saturn isn't the only ringed planet in our solar system, but none are as beautiful as Saturn's. Saturn has a total of 7 rings.",
        year: "29.45 Earth years",
        day: "10.7 hours",
        moons: 82,
        distanceFromSun: 9.5,
        meanTemp: -140,
        radius: 58232,
        timesLarger: 9.1,
        orbitalVelocity: 9.7, 
        orbitObject: "sun",
        orbitalRadius: 1433530000, 
        scaledOrbitalRadius: 108, 
        rotationVelocity: 9.87,
        orbitalInclination: 2.5,
        axialTilt: 26.73,
    },
    {
        name: "uranus",
        displayName: "Uranus",
        caption: "Ice Giant",
        description: "Uranus is an icy gas giant. It is the only planet in our solar system that rotates on its side. Just like Venus, Uranus also rotates east to west.",
        year: "84 Earth years",
        day: "17 hours",
        moons: 27,
        distanceFromSun: 19.8,
        meanTemp: -195,
        radius: 25362,
        timesLarger: 4,
        orbitalVelocity: 6.8, 
        orbitObject: "sun",
        orbitalRadius: 2870972000, 
        scaledOrbitalRadius: 145, 
        rotationVelocity: 2.59,
        orbitalInclination: 0.8,
        axialTilt: 82.23,
    },
    {
        name: "neptune",
        displayName: "Neptune",
        caption: "Big Blue Planet",
        description: "Neptune is the only planet in our solar system not visible to the naked eye. NASA's Voyager 2 flew by Neptune in 1989 making it the only spacecraft to visit it up close.",
        year: "164 Earth years",
        day: "16 hours",
        moons: 14,
        distanceFromSun: 30.1,
        meanTemp: -200,
        radius: 24622,
        timesLarger: 3.9,
        orbitalVelocity: 5.4, 
        orbitObject: "sun",
        orbitalRadius: 4514953000, 
        scaledOrbitalRadius: 180, 
        rotationVelocity: 2.6,
        orbitalInclination: 1.8,
        axialTilt: 28.32,
    },
    /* - - Sun - - */

    /* - - Moons - - */
    {
        name: "moon",
        displayName: "Earth's Moon",
        caption: "The brightest object in the night sky",
        description: "Earth's Moon is the fifth largest moon in our solar system. The Moon has so far had 24 human and more than 105 robotic visitors.",
        year: "27 days",
        radius: 1737.5,
        timesLarger: 0.27,
        distance: 385000,
        minTemp: -173,
        maxTemp: 127,
        orbitalVelocity: 1.022,
        orbitObject: "earth",
        orbitalRadius: 385000, 
        scaledOrbitalRadius: 3,
        rotationVelocity: 0.005,
        orbitalInclination: 5.1,
    },
    {
        name: "io",
        displayName: "Io",
        caption: "Most volcanic activity",
        description: "Io is so volcanically active that it has lakes made of lava. Some of its volcanoes are so powerful, that with a telescope they can be seen from Earth.",
        year: "42 hours",
        radius: 1821.6,
        timesLarger: 0.285,
        distance: 262000,
        meanTemp: -143,
        orbitalVelocity: 17.334,
        orbitObject: "jupiter",
        orbitalRadius: 262000, 
        scaledOrbitalRadius: 10,
        rotationVelocity: 0.07,
        orbitalInclination: 0.05,
    },
    {
        name: "europa",
        displayName: "Europa",
        caption: "Life promising moon",
        description: "Europa's subsurface ocean of salty water contains twice as much water as Earth's oceans. It is possible, that beneath its frozen surface exists some form of life.",
        year: "85 hours",
        radius: 1560.8,
        timesLarger: 0.24,
        distance: 670900,
        minTemp: -220,
        maxTemp: -160,
        orbitalVelocity: 13.743,
        orbitObject: "jupiter",
        orbitalRadius: 670900, 
        scaledOrbitalRadius: 13,
        rotationVelocity: 0.03,
        orbitalInclination: 0.47,
    },
    {
        name: "ganymede",
        displayName: "Ganymede",
        caption: "Largest moon in the Solar System",
        description: "Ganymede is a moon bigger than Mercury. Ganymede has underground oceans and a faint oxygen atmosphere. It is also only moon to have its own magnetic field.",
        year: "172 hours",
        radius: 2634.1,
        timesLarger: 0.416,
        distance: 1070400,
        minTemp: -180,
        maxTemp: -113,
        orbitalVelocity: 10.880,
        orbitObject: "jupiter",
        orbitalRadius: 1070400, 
        scaledOrbitalRadius: 15,
        rotationVelocity: 0.026,
        orbitalInclination: 0.2,
    },
    {
        name: "callisto",
        displayName: "Callisto",
        caption: "The long dead moon",
        description: "Callisto is the most heavily cratered object in our solar system. It has almost none geologic activity on its surface, but may contain oceans beneath the surface.",
        year: "17 days",
        radius: 2410.3,
        timesLarger: 0.384,
        distance: 1883000,
        minTemp: -193,
        maxTemp: -108,
        orbitalVelocity: 8.204,
        orbitObject: "jupiter",
        orbitalRadius: 1883000, 
        scaledOrbitalRadius: 17.5,
        rotationVelocity: 0.01,
        orbitalInclination: 0.28,
    },
    {
        name: "titan",
        displayName: "Titan",
        caption: "Moon with liquids on its surface",
        description: "Titan is the only moon in our solar system that has clouds and a dense atmosphere. There are also lakes and oceans on the surface, however they are made of methane and ethane.",
        year: "16 days",
        radius: 2574.7,
        timesLarger: 0.4,
        distance: 1221865,
        meanTemp: -179,
        orbitalVelocity: 5.57,
        orbitObject: "saturn",
        orbitalRadius: 1221865, 
        scaledOrbitalRadius: 16,
        rotationVelocity: 0.011,
        orbitalInclination: 0.33,
    },
    {
        name: "triton",
        displayName: "Triton",
        caption: "The coldest object in Solar system",
        description: "Triton is the coldest moon in our solar system. It is also the largest moon that orbits in the opposite direction of its planet's rotation.",
        year: "141 hours",
        radius: 1353.4,
        timesLarger: 0.21,
        distance: 354759,
        meanTemp: -235,
        orbitalVelocity: 4.39,
        orbitObject: "neptune",
        orbitalRadius: 354759, 
        scaledOrbitalRadius: 7,
        rotationVelocity: 0.017,
        orbitalInclination: 156.885,
    },
    /* - - Moons - - */
]