export const PLANETS = [
    /* - - Sun - - */
    {
        name: "sun",
        displayName: "The Sun",
        description: "Yellow dwarf star",
        year: "230 milion years",
        day: null,
        distanceFromSun: -1,
        radius: 695508,
        TimesLarger: 109.2,
        orbitalVelocity: 0,
        orbitObject: null,
        orbitalRadius: 0,
        scaledOrbitalRadius: 0,
        rotationVelocity: 2,
        orbitalInclination: 0,
        axialTilt: 7.25,
    },
    /* - - Sun - - */

    /* - - Planets - - */
    {
        name: "mercury",
        displayName: "Mercury",
        description: "Swift Planet",
        year: "88 Earth days",
        day: "59 Earth days",
        distanceFromSun: 0.4,
        radius: 2439.7,
        TimesLarger: 0.38,
        orbitalVelocity: 47.9, 
        orbitObject: "sun",
        orbitalRadius: 57909050, 
        scaledOrbitalRadius: 24, 
        rotationVelocity: 0.003,
        orbitalInclination: 7,
        axialTilt: 0.03,
    },
    {
        name: "venus",
        displayName: "Venus",
        description: "Morning Star",
        year: "225 Earth days",
        day: "243 Earth days",
        distanceFromSun: 0.7,
        radius: 6051.8,
        TimesLarger: 0.9,
        orbitalVelocity: 35.0, 
        orbitObject: "sun",
        orbitalRadius: 108200000, 
        scaledOrbitalRadius: 31, 
        rotationVelocity: 0.003,
        orbitalInclination: 3.4,
        axialTilt: 2.64	,
    },
    {
        name: "earth",
        displayName: "Earth",
        description: "Blue Planet",
        year: "365.25 Earth days",
        day: "23.9 hours",
        distanceFromSun: 1,
        radius: 6371,
        TimesLarger: -1,
        orbitalVelocity: 29.8, //29.8
        orbitObject: "sun",
        orbitalRadius: 149600000, 
        scaledOrbitalRadius: 37, //149.6, //149600000 // Scale: 1m : 1 000 000km
        rotationVelocity: 0.46,
        orbitalInclination: 0,
        axialTilt: 23.44,
    },
    {
        name: "mars",
        displayName: "Mars",
        description: "Red Planet",
        year: "1.88 Earth years",
        day: "24.6 hours",
        distanceFromSun: 1.5,
        radius: 3389.5,
        TimesLarger: 0.52,
        orbitalVelocity: 24.1, 
        orbitObject: "sun",
        orbitalRadius: 227939366, 
        scaledOrbitalRadius: 45, 
        rotationVelocity: 0.241,
        orbitalInclination: 1.8,
        axialTilt: 25.19,
    },
    {
        name: "jupiter",
        displayName: "Jupiter",
        description: "Giant Planet",
        year: "11.86 Earth years",
        day: "9.93 hours",
        distanceFromSun: 5.1,
        radius: 69911,
        TimesLarger: 11,
        orbitalVelocity: 24.1, 
        orbitObject: "sun",
        orbitalRadius: 778412027, 
        scaledOrbitalRadius: 72, 
        rotationVelocity: 12.6,
        orbitalInclination: 1.3,
        axialTilt: 3.13,
    },
    {
        name: "saturn",
        displayName: "Saturn",
        description: "Ringed Planet",
        year: "29.45 Earth years",
        day: "10.7 hours",
        distanceFromSun: 9.5,
        radius: 58232,
        TimesLarger: 9.1,
        orbitalVelocity: 9.7, 
        orbitObject: "sun",
        orbitalRadius: 1433530000, 
        scaledOrbitalRadius: 108, 
        rotationVelocity: 9.87,
        orbitalInclination: 2.5,
        axialTilt: 26.73,
    },
    {
        name: "uranus",
        displayName: "Uranus",
        description: "Ice Giant",
        year: "84 Earth years",
        day: "17 hours",
        distanceFromSun: 19.8,
        radius: 25362,
        TimesLarger: 4,
        orbitalVelocity: 6.8, 
        orbitObject: "sun",
        orbitalRadius: 2870972000, 
        scaledOrbitalRadius: 145, 
        rotationVelocity: 2.59,
        orbitalInclination: 0.8,
        axialTilt: 82.23,
    },
    {
        name: "neptune",
        displayName: "Neptune",
        description: "Big Blue Planet",
        year: "164 Earth years",
        day: "16 hours",
        distanceFromSun: 30.1,
        radius: 24622,
        TimesLarger: 3.9,
        orbitalVelocity: 5.4, 
        orbitObject: "sun",
        orbitalRadius: 4514953000, 
        scaledOrbitalRadius: 180, 
        rotationVelocity: 2.6,
        orbitalInclination: 1.8,
        axialTilt: 28.32,
    },
    /* - - Sun - - */

    /* - - Moons - - */
    {
        name: "moon",
        displayName: "Earth's Moon",
        description: "The brightest object in the night sky",
        year: "27 days",
        radius: 1737.5,
        TimesLarger: 0.27,
        distance: "385000 km",
        orbitalVelocity: 1.022,
        orbitObject: "earth",
        orbitalRadius: 385000, 
        scaledOrbitalRadius: 3,
        rotationVelocity: 0.005,
        orbitalInclination: 5.1,
    },
    {
        name: "io",
        displayName: "Io",
        description: "Most volcanic activity",
        year: "42 hours",
        radius: 1821.6,
        TimesLarger: 0.285,
        distance: "262000 km",
        orbitalVelocity: 17.334,
        orbitObject: "jupiter",
        orbitalRadius: 262000, 
        scaledOrbitalRadius: 10,
        rotationVelocity: 0.07,
        orbitalInclination: 0.05,
    },
    {
        name: "europa",
        displayName: "Europa",
        description: "Life promising moon",
        year: "85 hours",
        radius: 1560.8,
        TimesLarger: 0.24,
        distance: "670900 km",
        orbitalVelocity: 13.743,
        orbitObject: "jupiter",
        orbitalRadius: 670900, 
        scaledOrbitalRadius: 13,
        rotationVelocity: 0.03,
        orbitalInclination: 0.47,
    },
    {
        name: "ganymede",
        displayName: "Ganymede",
        description: "Largest moon in the Solar System",
        year: "172 hours",
        radius: 2634.1,
        TimesLarger: 0.416,
        distance: "1070400 km",
        orbitalVelocity: 10.880,
        orbitObject: "jupiter",
        orbitalRadius: 1070400, 
        scaledOrbitalRadius: 15,
        rotationVelocity: 0.026,
        orbitalInclination: 0.2,
    },
    {
        name: "callisto",
        displayName: "Callisto",
        description: "The long dead moon",
        year: "17 days",
        radius: 2410.3,
        TimesLarger: 0.384,
        distance: "1883000 km",
        orbitalVelocity: 8.204,
        orbitObject: "jupiter",
        orbitalRadius: 1883000, 
        scaledOrbitalRadius: 17.5,
        rotationVelocity: 0.01,
        orbitalInclination: 0.28,
    },
    {
        name: "titan",
        displayName: "Titan",
        description: "Moon with liquids on its surface",
        year: "16 days",
        radius: 2574.7,
        TimesLarger: 0.4,
        distance: "1221865 km",
        orbitalVelocity: 5.57,
        orbitObject: "saturn",
        orbitalRadius: 1221865, 
        scaledOrbitalRadius: 16,
        rotationVelocity: 0.011,
        orbitalInclination: 0.33,
    },
    {
        name: "triton",
        displayName: "Triton",
        description: "The coldest object in Solar system",
        year: "141 hours",
        radius: 1353.4,
        TimesLarger: 0.21,
        distance: "354759 km",
        orbitalVelocity: 4.39,
        orbitObject: "neptune",
        orbitalRadius: 354759, 
        scaledOrbitalRadius: 7,
        rotationVelocity: 0.017,
        orbitalInclination: 156.885,
    },
    /* - - Moons - - */
]